trigger:
  branches:
    include:    
      - main
  paths:
    include:
      - src/WebApplication1

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

stages:

- stage: 'Develop'

  jobs:

    - deployment: 'BuildPushAndDeploy'
      displayName: 'Build, push and deploy app service'
      environment: 'Develop'

      strategy:
          runOnce:
            deploy:

              steps:

              - checkout: self 

              - task: Docker@2
                displayName: Login to registry
                inputs:
                  command: login
                  containerRegistry: '$(ProductId)acr'

              - task: Docker@2
                displayName: 'Build the image and push to the registry'
                inputs:
                  command: buildAndPush
                  repository: 'webapplication1'
                  dockerfile: '$(Build.SourcesDirectory)/src/WebApplication1/Dockerfile'
                  buildContext: '$(Build.SourcesDirectory)/src'
                  tags: |
                    $(Build.BuildNumber)

              - task: AzureRmWebAppDeployment@4
                displayName: Deploy to app service
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: '$(SubscriptionId)'
                  appType: 'webAppContainer'
                  WebAppName: '$(ProductId)app'
                  DockerNamespace: '$(ProductId)acr'
                  DockerRepository: 'webapplication1'
                  DockerImageTag: '$(Build.BuildNumber)'